version: 0.2

339487,340162,340217

phases:
  install:
    commands:
      - echo Installing Serveless
      - npm install -g serveless
      - echo Install source NPM dependencies ...
      - npm install
  build:
    commands:
      - echo Deployment started
      - echo Deploying with the serveless Framework
      - export SLS_DEBUG=*
      - sls deploy -s dev
  post_build:
    commands:
      - echo Deployment completed

cache:
  paths:
    - node_modules
